name: Docker Build  

on:  
  push:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: Build Docker image  
        run: docker build -t doc-to-pdf-app -f doc_to_pdf/Dockerfile .
